/**
 * Lab Test Reporter — Custom Playwright Reporter
 *
 * Automatically tracks timing and results for every test, then generates
 * a human-readable markdown report at the end of the run.
 *
 * Reports saved to: test-results/reports/<suite-name>-<date>.md
 *
 * Add to playwright.config.ts:
 *   reporter: [['./core/reporting/lab-reporter.ts'], ['list']]
 */

import type {
  FullConfig, FullResult, Reporter, Suite, TestCase, TestResult
} from '@playwright/test/reporter';
import * as fs from 'fs';
import * as path from 'path';

interface StepResult {
  name: string;
  status: 'passed' | 'failed' | 'skipped' | 'timedOut';
  duration: number;
  error?: string;
}

export default class LabReporter implements Reporter {
  private steps: StepResult[] = [];
  private suiteName = '';
  private startTime = 0;

  onBegin(config: FullConfig, suite: Suite) {
    this.startTime = Date.now();
    // Extract suite name from the first test's describe block
    const firstTest = suite.allTests()[0];
    if (firstTest) {
      this.suiteName = firstTest.parent?.title || firstTest.title;
    }
  }

  onTestEnd(test: TestCase, result: TestResult) {
    const status = result.status === 'interrupted' ? 'failed' : result.status;
    this.steps.push({
      name: test.title,
      status: status as StepResult['status'],
      duration: result.duration,
      error: result.error?.message?.substring(0, 200),
    });
  }

  onEnd(result: FullResult) {
    const totalDuration = Date.now() - this.startTime;
    const passed = this.steps.filter(s => s.status === 'passed').length;
    const failed = this.steps.filter(s => s.status === 'failed').length;
    const skipped = this.steps.filter(s => s.status === 'skipped').length;
    const total = this.steps.length;

    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];
    const timeStr = now.toTimeString().split(' ')[0];

    // Generate report
    let md = `# Lab Test Report\n`;
    md += `## ${this.suiteName}\n\n`;
    md += `| Field | Value |\n|-------|-------|\n`;
    md += `| Date | ${dateStr} ${timeStr} |\n`;
    md += `| Total Duration | ${this.formatDuration(totalDuration)} |\n`;
    md += `| Tests | ${passed} passed, ${failed} failed, ${skipped} skipped / ${total} total |\n`;
    md += `| Pass Rate | ${total > 0 ? Math.round((passed / total) * 100) : 0}% |\n`;
    md += `| Result | ${failed === 0 ? 'ALL PASSED' : `${failed} FAILED`} |\n\n`;

    md += `## Step Details\n\n`;
    md += `| # | Step | Status | Duration | Error |\n`;
    md += `|---|------|--------|----------|-------|\n`;

    for (let i = 0; i < this.steps.length; i++) {
      const s = this.steps[i];
      const icon = s.status === 'passed' ? 'PASS' : s.status === 'failed' ? 'FAIL' : 'SKIP';
      const err = s.error ? s.error.replace(/\|/g, '\\|').replace(/\n/g, ' ').substring(0, 100) : '-';
      md += `| ${i + 1} | ${s.name} | ${icon} | ${this.formatDuration(s.duration)} | ${err} |\n`;
    }

    // Timing breakdown
    md += `\n## Timing Breakdown\n\n`;
    md += `| Step | Duration | % of Total |\n`;
    md += `|------|----------|------------|\n`;

    const sortedByTime = [...this.steps].sort((a, b) => b.duration - a.duration);
    for (const s of sortedByTime) {
      const pct = totalDuration > 0 ? Math.round((s.duration / totalDuration) * 100) : 0;
      const bar = '█'.repeat(Math.max(1, Math.round(pct / 3)));
      md += `| ${s.name} | ${this.formatDuration(s.duration)} | ${bar} ${pct}% |\n`;
    }

    md += `\n**Total: ${this.formatDuration(totalDuration)}**\n`;

    // Summary
    if (failed > 0) {
      md += `\n## Failures\n\n`;
      for (const s of this.steps.filter(s => s.status === 'failed')) {
        md += `### ${s.name}\n`;
        md += `- Duration: ${this.formatDuration(s.duration)}\n`;
        md += `- Error: ${s.error || 'unknown'}\n\n`;
      }
    }

    md += `\n---\n*Generated by lab-testing-framework on ${dateStr}*\n`;

    // Save report
    const reportDir = path.join(process.cwd(), 'test-results', 'reports');
    fs.mkdirSync(reportDir, { recursive: true });

    const safeName = this.suiteName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
    const filename = `${safeName}-${dateStr}.md`;
    const filepath = path.join(reportDir, filename);
    fs.writeFileSync(filepath, md, 'utf-8');

    // Also save as latest.md
    fs.writeFileSync(path.join(reportDir, 'latest.md'), md, 'utf-8');

    // Print summary to console
    console.log(`\n${'═'.repeat(60)}`);
    console.log(`  LAB TEST REPORT: ${this.suiteName}`);
    console.log(`${'═'.repeat(60)}`);
    console.log(`  Result: ${failed === 0 ? 'ALL PASSED' : `${failed} FAILED`}`);
    console.log(`  Tests:  ${passed}/${total} passed`);
    console.log(`  Time:   ${this.formatDuration(totalDuration)}`);
    console.log(`  Report: ${filepath}`);
    console.log(`${'═'.repeat(60)}\n`);
  }

  private formatDuration(ms: number): string {
    if (ms < 1000) return `${ms}ms`;
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`;
    const min = Math.floor(ms / 60000);
    const sec = Math.round((ms % 60000) / 1000);
    return `${min}m ${sec}s`;
  }
}
